# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegrab < Formula
  desc "An interactive CLI tool for selecting and bundling code into a single, LLM-ready output file"
  homepage "https://github.com/epilande/codegrab"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/epilande/codegrab/releases/download/v1.0.2/codegrab_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "af8c17cb72712c109d89a2b57e77620104124f9debb30bf6365a6ec18bd51e58"

      def install
        bin.install "grab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/epilande/codegrab/releases/download/v1.0.2/codegrab_1.0.2_Darwin_arm64.tar.gz"
      sha256 "c1f526c07607efa98e929d770b9ebbe10df2ca63cdafe046d8f9968ed1f50f18"

      def install
        bin.install "grab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/epilande/codegrab/releases/download/v1.0.2/codegrab_1.0.2_Linux_x86_64.tar.gz"
        sha256 "6b2bfb65dfb39b6a27e45e7bbc83a9ac8e2122352eb9b088bf036c4688dd5abd"

        def install
          bin.install "grab"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/epilande/codegrab/releases/download/v1.0.2/codegrab_1.0.2_Linux_arm64.tar.gz"
        sha256 "db26861362ac83ab769d285ea2e2eab8061a043be4538d977b28722d41c672bf"

        def install
          bin.install "grab"
        end
      end
    end
  end

  test do
    system "#{bin}/grab --version"
  end
end
