# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegrab < Formula
  desc "An interactive CLI tool for selecting and bundling code into a single, LLM-ready output file"
  homepage "https://github.com/epilande/codegrab"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/epilande/codegrab/releases/download/v1.1.0/codegrab_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "310c15d2128b74007a5d6bba5cddc0660b43d0064583046f81db5bdbd352fb92"

      def install
        bin.install "grab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/epilande/codegrab/releases/download/v1.1.0/codegrab_1.1.0_Darwin_arm64.tar.gz"
      sha256 "3ad94098f3bfd047fba7d8de57d53d5d139855307d0d0d0259e349b4d109aca0"

      def install
        bin.install "grab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/epilande/codegrab/releases/download/v1.1.0/codegrab_1.1.0_Linux_x86_64.tar.gz"
      sha256 "2ad2ff8ce5b652e4ff6252ef0ef15cafc74311969ae39c25b525f8b528550609"
      def install
        bin.install "grab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/epilande/codegrab/releases/download/v1.1.0/codegrab_1.1.0_Linux_arm64.tar.gz"
      sha256 "677e4e28ec01916280b903e9225b297d8df64f12263ad2f0c27b5ba299905789"
      def install
        bin.install "grab"
      end
    end
  end

  test do
    system "#{bin}/grab --version"
  end
end
